### ISSUE TITLE
Should the game objects have method update?

### ISSUE THREAD

**Issue by SimoPrG** [TeamMoscowMule/MultitaskGame#1]
Hi team, the idea beheind the game object's method update was that each object could change its state. I think that this could force the object to know about other objects in the game which is not right.
I would like to ask for your opinion if it is better each game to update the states of its objects.

**Comment by TsvetanRazsolkov** [comment]
Hi. I think it's OK to have such method "update" for each object, which will be called in the game. For the moment we can detect eventual collisions in it, until we have something working as a game. Then it will not be difficult to make a separate module "colisionManager" or something like that, which will have methods accepting all collidable objects and returning "true" or "false", if there is/isn't a collision,  to be used in the update method.

**Comment by SimoPrG** [comment]
Today I mentioned to @NikolayIT about our game. I shared our problem with him and he adviced me that it is best in general to have a separete class to handle the gameObjects, so the game class is not forced to know about the gameObjects details.
